package org.te.app.android.assertionConstants.samsung;

public class FoodDrinksScreenConstants {

    public static String TITLE = "Food & Drinks";
    public static String[] CUISINES = {
            "American",
            "Arabic",
            "Chinese",
            "Indian",
            "Italian",
            "African",
            "Argentinian",
            "Asian",
            "Asian Fusion",
            "Australian",
            "Baked Goods",
            "Bar Food",
            "Belgian",
            "Beverages",
            "Brazilian",
            "British",
            "Burger Joint",
            "Café",
            "Caribbean",
            "Cuban",
            "Desserts",
            "Egyptian",
            "Emirati",
            "European",
            "Fast Food",
            "Filipino",
            "French",
            "Fusion",
            "German",
            "Greek",
            "Healthy",
            "Ice Cream",
            "Informal Dining",
            "International",
            "Japanese",
            "Korean",
            "Latin American",
            "Lebanese",
            "Malaysian",
            "Maltese",
            "Mediterranean",
            "Mexican",
            "Middle Eastern",
            "Modern Australian",
            "Moroccan",
            "Nepalese",
            "Other",
            "Pan-Asian",
            "Persian",
            "Peruvian",
            "Pizza",
            "Portuguese",
            "Russian",
            "Seafood",
            "Spanish",
            "Sri Lankan",
            "Steakhouse",
            "Tapas",
            "Thai",
            "Turkish",
            "Vegan",
            "Vegetarian",
            "Vietnamese",
            "Yogurt"
    };

    public static String[] TYPES = {
            "All",
            "Cafés",
            "Casual Dining",
            "Fine Dining",
            "Informal Dining & Takeaway",
            "Pubs, Bars & Clubs"
    };

    public static String[] AMENITY = {
            "Alcohol",
            "Buffet" ,
            "Halal" ,
            "Kids Welcome" ,
            "Live Entertainment" ,
            "Outdoor Cooling" ,
            "Outdoor Heating" ,
            "Outdoor Seating" ,
            "Parking" ,
            "Pets Allowed" ,
            "Pork Products" ,
            "Smoking - Indoor" ,
            "Smoking - Shisha" ,
            "Sports Screens" ,
            "Supervised Play Area" ,
            "Takeaway" ,
            "Valet Parking" ,
            "Wheelchair Accessible" ,
            "Wi-Fi" ,
            "Wineries",
            "Rooftop Bars"
    };

}
